# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Progress Columns on Labels

on:
  issues:
    types: [labeled]

jobs:
  accept-feature-request:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_SECRET }}"
        project-url: "https://github.com/sabinmarcu/crafting-works/projects/2"
        column-name: "Accepted"
        label-name: "feat"
  deny-feature-request:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_SECRET }}"
        project-url: "https://github.com/sabinmarcu/crafting-works/projects/2"
        column-name: "Denied"
        label-name: "wontdo"
  move-to-in-progress-backlog:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_SECRET }}"
        project-url: "https://github.com/sabinmarcu/crafting-works/projects/1"
        column-name: "In progress"
        label-name: "in-progress"
  move-to-in-progress-planning:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.LABEL_SECRET }}"
        project-url: "https://github.com/sabinmarcu/crafting-works/projects/2"
        column-name: "In Progress"
        label-name: "in-progress"
