name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign Feature Requests to Planning
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'feature request') ||
        contains(github.event.pull_request.labels.*.name, 'feature request')
      with:
        project: 'https://github.com/sabinmarcu/minecraft-calculator/projects/2'

    - name: Assign Bugs to Backlog
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/sabinmarcu/minecraft-calculator/projects/1'
        column_name: 'Labeled'
